---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maurocastro/public_html/
    - /index.html $DEPLOYPATH
    - /css -R css/ $DEPLOYPATH
    - /img -R img/ $DEPLOYPATH
    - /js -R js/ $DEPLOYPATH
