---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maurocastro/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R css/ $DEPLOYPATH
    - /bin/cp -R img/ $DEPLOYPATH
    - /bin/cp -R js/ $DEPLOYPATH
